name: caijingjj

on:
  workflow_dispatch:
  schedule:
    - cron: '55 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caijingjj
        env:
          cszl9: ${{ secrets.cszl9 }}
        run: |
          echo $cszl9 | jq -r .illq87 | /bin/bash
          echo $vebmq7214 | jq -r .jv15734 | /bin/bash
          echo $yn3 | jq -r .aa788 | /bin/bash
          echo $tazbk026 | jq -r .eklb1121 | /bin/bash

